name: backend-automation-ci
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
<<<<<<< HEAD
      FORCE_HARD_SASL: true
=======
      SOFT_ASSERT_SASL: true
>>>>>>> 12cc977 (chore: initial commit - backend automation v6)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Run tests
        run: mvn -B -q -DskipTests=false test
      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/**
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results/**