name: release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      FORCE_HARD_SASL: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run tests
        run: mvn -B -q -DskipTests=false test

      - name: Generate Allure report
        run: mvn -q allure:report

      - name: Archive artifacts
        run: |
          mkdir -p dist
          cp -r target/surefire-reports dist/surefire-reports || true
          cp -r target/allure-results dist/allure-results || true
          cp -r target/site/allure-maven-plugin dist/allure-report || true
          tar -czf securitease-backend-automation-artifacts.tgz dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: securitease-backend-automation-artifacts.tgz